name: Monkeytype Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '8 0 * * *'

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: vnphanquang/monkeytype-readme@main
        with:
          # required:
          monkeytype_api_key: ${{ secrets.MONKEYTYPE_API_KEY }}
          mode: 'words'
          mode2: '50'
          # not required with default:
          style: 'for-the-badge'
          logoVariant: 'one'
          label: 'monkeytype'
